from . import res_partner
from . import product_template
from . import sale_order
from . import crm_lead
from . import school_year
from . import internship_type
from . import school_year_historical
from . import internship_documentation
from . import res_config_settings
